#!/usr/bin/env python3
"""
Wrapper script to run Rscript with timeout and check for output file.
Used for capturing plots from interactive R scripts.
"""
import subprocess
import sys
import os
import time

def main():
    if len(sys.argv) < 4:
        print("Usage: run_with_timeout.py <timeout_seconds> <output_file> <rscript> [rscript_args...]")
        sys.exit(1)
    
    timeout_seconds = int(sys.argv[1])
    output_file = sys.argv[2]
    rscript = sys.argv[3]
    rscript_args = sys.argv[4:] if len(sys.argv) > 4 else []
    
    # Run Rscript with timeout
    # Pass all arguments to Rscript
    try:
        cmd = ['Rscript', '--vanilla', rscript] + rscript_args
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            bufsize=1
        )
        
        # Wait up to timeout_seconds
        try:
            stdout, _ = proc.communicate(timeout=timeout_seconds)
            exit_code = proc.returncode
            print(stdout, end='')
        except subprocess.TimeoutExpired:
            # Timeout is expected - plot should be generated by now
            print('Timeout occurred (expected) - plot should be generated...', file=sys.stderr)
            proc.kill()
            stdout, _ = proc.communicate()
            print(stdout, end='')
            exit_code = 124  # Timeout exit code
    except Exception as e:
        print(f'Error running Rscript: {e}', file=sys.stderr)
        exit_code = 1
    
    # Check if output file exists
    if os.path.exists(output_file) and os.path.getsize(output_file) > 0:
        print(f'SUCCESS: Output file created: {output_file}', file=sys.stderr)
        sys.exit(0)
    elif exit_code == 124:
        # Timeout occurred - give it a moment and check again
        time.sleep(3)
        if os.path.exists(output_file) and os.path.getsize(output_file) > 0:
            print(f'SUCCESS: Output file found after timeout: {output_file}', file=sys.stderr)
            sys.exit(0)
        else:
            print(f'ERROR: Output file not found after timeout: {output_file}', file=sys.stderr)
            sys.exit(1)
    else:
        print(f'ERROR: Script failed with exit code: {exit_code}', file=sys.stderr)
        sys.exit(exit_code)

if __name__ == '__main__':
    main()

